<!DOCTYPE html>
<html lang="en-us">
  <head>
    
    <meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="generator" content="Hugo 0.51 with theme Tranquilpeak 0.4.3-SNAPSHOT">
<meta name="author" content="Jagger Villalobos">
<meta name="keywords" content="">
<meta name="description" content="Using Airbnb By now, most Gen Z and millenials have heard of or used Airbnb for a range of many reasons, such as looking for a place to crash or taking a vacation. I believe what won the consumer’s attention over hotels was the fact that you are getting the “homey” setting and privacy while away on vacation instead of a hotel environment. I realize not everyone wants to part ways with room service, benefits of a having full-service bar in the lobby, pool &amp; spas, sometimes a gym, and the 100&#43; channels, but when comparing the prices and the extra sq.">


<meta property="og:description" content="Using Airbnb By now, most Gen Z and millenials have heard of or used Airbnb for a range of many reasons, such as looking for a place to crash or taking a vacation. I believe what won the consumer’s attention over hotels was the fact that you are getting the “homey” setting and privacy while away on vacation instead of a hotel environment. I realize not everyone wants to part ways with room service, benefits of a having full-service bar in the lobby, pool &amp; spas, sometimes a gym, and the 100&#43; channels, but when comparing the prices and the extra sq.">
<meta property="og:type" content="article">
<meta property="og:title" content="Teaching a Machine to Learn NYC Airbnb Prices">
<meta name="twitter:title" content="Teaching a Machine to Learn NYC Airbnb Prices">
<meta property="og:url" content="/2018/11/ml-airbnb-prices/">
<meta property="twitter:url" content="/2018/11/ml-airbnb-prices/">
<meta property="og:site_name" content="Jagger with Swagger">
<meta property="og:description" content="Using Airbnb By now, most Gen Z and millenials have heard of or used Airbnb for a range of many reasons, such as looking for a place to crash or taking a vacation. I believe what won the consumer’s attention over hotels was the fact that you are getting the “homey” setting and privacy while away on vacation instead of a hotel environment. I realize not everyone wants to part ways with room service, benefits of a having full-service bar in the lobby, pool &amp; spas, sometimes a gym, and the 100&#43; channels, but when comparing the prices and the extra sq.">
<meta name="twitter:description" content="Using Airbnb By now, most Gen Z and millenials have heard of or used Airbnb for a range of many reasons, such as looking for a place to crash or taking a vacation. I believe what won the consumer’s attention over hotels was the fact that you are getting the “homey” setting and privacy while away on vacation instead of a hotel environment. I realize not everyone wants to part ways with room service, benefits of a having full-service bar in the lobby, pool &amp; spas, sometimes a gym, and the 100&#43; channels, but when comparing the prices and the extra sq.">
<meta property="og:locale" content="en-us">

  
    <meta property="article:published_time" content="2018-11-19T00:00:00">
  
  
    <meta property="article:modified_time" content="2018-11-19T00:00:00">
  
  
  
    
      <meta property="article:section" content="R">
    
      <meta property="article:section" content="R Markdown">
    
      <meta property="article:section" content="Predictions">
    
      <meta property="article:section" content="Programming">
    
  
  
    
      <meta property="article:tag" content="Project">
    
      <meta property="article:tag" content="Machine Learning">
    
      <meta property="article:tag" content="Airbnb">
    
      <meta property="article:tag" content="Price Predictions">
    
      <meta property="article:tag" content="Programming">
    
  


<meta name="twitter:card" content="summary">








  <meta property="og:image" content="https://res.cloudinary.com/dyackvnwm/image/upload/v1542650457/Untitled-design-18.png">
  <meta property="twitter:image" content="https://res.cloudinary.com/dyackvnwm/image/upload/v1542650457/Untitled-design-18.png">




  <meta property="og:image" content="https://res.cloudinary.com/dyackvnwm/image/upload/v1542411893/profilepic.png">
  <meta property="twitter:image" content="https://res.cloudinary.com/dyackvnwm/image/upload/v1542411893/profilepic.png">


    <title>Teaching a Machine to Learn NYC Airbnb Prices</title>

    <link rel="icon" href="/favicon.png">
    

    

    <link rel="canonical" href="/2018/11/ml-airbnb-prices/">

    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha256-eZrrJcwDc/3uDhsdt61sL2oOBY362qM3lon1gyExkL0=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.4/jquery.fancybox.min.css" integrity="sha256-vuXZ9LGmmwtjqFX1F+EKin1ThZMub58gKULUyf0qECk=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.4/helpers/jquery.fancybox-thumbs.min.css" integrity="sha256-SEa4XYAHihTcEP1f5gARTB2K26Uk8PsndQYHQC1f4jU=" crossorigin="anonymous" />
    
    
    <link rel="stylesheet" href="/css/style-nnm2spxvve8onlujjlegkkytaehyadd4ksxc1hyzzq9a2wvtrgbljqyulomn.min.css" />
    
    

    
      
    
    
  </head>

  <body>
    <div id="blog">
      <header id="header" data-behavior="4">
  <i id="btn-open-sidebar" class="fa fa-lg fa-bars"></i>
  <div class="header-title">
    <a class="header-title-link" href="/">Jagger with Swagger</a>
  </div>
  
    
      <a class="header-right-picture "
         href="/#about">
    
    
    
      
        <img class="header-picture" src="https://res.cloudinary.com/dyackvnwm/image/upload/v1542411893/profilepic.png" alt="Author&#39;s picture" />
      
    
    </a>
  
</header>

      <nav id="sidebar" data-behavior="4">
  <div class="sidebar-container">
    
      <div class="sidebar-profile">
        <a href="/#about">
          <img class="sidebar-profile-picture" src="https://res.cloudinary.com/dyackvnwm/image/upload/v1542411893/profilepic.png" alt="Author&#39;s picture" />
        </a>
        <h4 class="sidebar-profile-name">Jagger Villalobos</h4>
        
          <h5 class="sidebar-profile-bio">Model &amp; Forecast | Bottom-Up Investor | Equity Researcher</h5>
        
      </div>
    
    <ul class="sidebar-buttons">
      
  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="/">
    
      <i class="sidebar-button-icon fa fa-lg fa-home"></i>
      
      <span class="sidebar-button-desc">Home</span>
    </a>
  </li>

  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="/#about">
    
      <i class="sidebar-button-icon fa fa-lg fa-question"></i>
      
      <span class="sidebar-button-desc">About</span>
    </a>
  </li>

  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="/categories">
    
      <i class="sidebar-button-icon fa fa-lg fa-bookmark"></i>
      
      <span class="sidebar-button-desc">Categories</span>
    </a>
  </li>

  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="/tags">
    
      <i class="sidebar-button-icon fa fa-lg fa-tags"></i>
      
      <span class="sidebar-button-desc">Tags</span>
    </a>
  </li>

  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="/archives">
    
      <i class="sidebar-button-icon fa fa-lg fa-archive"></i>
      
      <span class="sidebar-button-desc">Archives</span>
    </a>
  </li>


    </ul>
    <ul class="sidebar-buttons">
      
  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="https://github.com/jagg19">
    
      <i class="sidebar-button-icon fa fa-lg fa-github"></i>
      
      <span class="sidebar-button-desc">GitHub</span>
    </a>
  </li>

  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="https://linkedin.com/in/jaggervillalobos">
    
      <i class="sidebar-button-icon fa fa-lg fa-linkedin"></i>
      
      <span class="sidebar-button-desc">Linkedin</span>
    </a>
  </li>


    </ul>
    <ul class="sidebar-buttons">
      

    </ul>
  </div>
</nav>

      
  <div class="post-header-cover
              text-left
              post-header-cover--partial"
       style="background-image:url('https://res.cloudinary.com/dyackvnwm/image/upload/v1542650457/Untitled-design-18.png')"
       data-behavior="4">
    
      <div class="post-header main-content-wrap text-left">
  
    <h1 class="post-title" itemprop="headline">
      Teaching a Machine to Learn NYC Airbnb Prices
    </h1>
  
  
  <div class="postShorten-meta post-meta">
    
      <time itemprop="datePublished" datetime="2018-11-19T00:00:00Z">
        
  November 19, 2018

      </time>
    
    
  
  
    <span>in</span>
    
      <a class="category-link" href="/categories/r">R</a>, 
    
      <a class="category-link" href="/categories/r-markdown">R Markdown</a>, 
    
      <a class="category-link" href="/categories/predictions">Predictions</a>, 
    
      <a class="category-link" href="/categories/programming">Programming</a>
    
  

  </div>

</div>
    
  </div>


      <div id="main" data-behavior="4"
        class="hasCover
               hasCoverMetaIn
               ">
        <article class="post" itemscope itemType="http://schema.org/BlogPosting">
          
          
          <div class="post-content markdown" itemprop="articleBody">
            <div class="main-content-wrap">
              


<div id="using-airbnb" class="section level1">
<h1>Using Airbnb</h1>
<p>By now, most Gen Z and millenials have heard of or used Airbnb for a range of many reasons, such as looking for a place to crash or taking a vacation. I believe what won the consumer’s attention over hotels was the fact that you are getting the “homey” setting and privacy while away on vacation instead of a hotel environment. I realize not everyone wants to part ways with room service, benefits of a having full-service bar in the lobby, pool &amp; spas, sometimes a gym, and the 100+ channels, but when comparing the prices and the extra sq. footage, it is hard not to take a look at and possibly book Airbnb listings.</p>
</div>
<div id="listing-on-airbnb" class="section level1">
<h1>Listing on Airbnb</h1>
<p>While most of us have used or considered booking an Airbnb, there are a lot less of us who have considered posting our own property on Airbnb. Being that I am infatuated with profit and New York City rent is extremely high, I considered listing my Brooklyn apartment to see what kind of profits I could turn. At the time, I was learning about multiple linear regression in my Quantitative Analysis &amp; Forecasting class and I was given a project to create a linear model to predict some form of dependent variable. I figured why not use this opportunity to dig a little deeper on estimating a listing price for my apartment. This led me to stumble upon pretty interesting information about commercial operators listings on Airbnb in New York City. To keep this post in line with the subject, I will just quickly summarize what I found in the following paragraph.</p>
</div>
<div id="commercial-operators" class="section level1">
<h1>Commercial Operators</h1>
<p>What exactly is a commercial operator? This is an Airbnb host that has multiple entire-home listings or controls many private-room listings. If I was to post on Airbnb to try and squeeze a profit, I would list my property for certain days or weeks of the month, and at most a rental property if I happened to own one. This compares to commercial operators who may have 4-6 entire home listings and 8-12 private room listings. It was estimated that commercial operators make up 12% of NYC Airbnb hosts, but earned almost 1/3 of all incoming revenue.</p>
</div>
<div id="why-is-this-an-issue" class="section level1">
<h1>Why is this an issue?</h1>
<p>I believe it is an issue because it is depleting the actual prices hosts could get for their properties if they were to list on Airbnb. If it weren’t for commercial operators saturating the market with these lower-priced listings, maybe I could squeeze an extra $20-30/ night from my listing. Think of these NYC commercial operators as the Walmart or Amazon of property listings. They often charge less per night than other hosts do across all listings and adjust their rates to attract a high number of rentals overall. To summarize, they are flooding the New York City markets with lower-priced listings.</p>
</div>
<div id="now-the-fun-stuff---building-the-model" class="section level1">
<h1>Now the fun stuff - Building the Model</h1>
<p>I found my data off of InsideAirBnb.com which is an independent, non-commercial set of tools and data that allows you to explore how Airbnb is really being used in cities around the world. I retrieved all listings in NYC as of 03/2018. This was a very large data set that contained 29,142 listings in NYC with 96 different factors to choose from as my independent variables. I would like to keep in mind the effect commercial operators have on prices. I believe that Airbnb listing prices are not fully predictable by the usual variables one would use to predict the price of a traditional property in NYC. These usual variables are factors such as bedroom count, bathroom, location, property type, and etc. If the listing prices were fully explainable by these usual variables, then I would assume with our data we will be able to train and build our model strong enough to have a low root mean squared error (RMSE). See below for how I got to our final Model.</p>
</div>
<div id="the-process" class="section level1">
<h1>The Process</h1>
<p>After loading in the data, I began to analyze the structure to search for any outliers or missing values. Our initial data set has a dimension of 29142 rows and 96 columns so let’s begin cutting down the amount of factors playing into the pricing. I will choose the variables that make the most sense when predicting a price for a property.</p>
<div id="cleaning-the-data" class="section level4">
<h4>Cleaning the Data</h4>
<pre class="r"><code>trimData &lt;-subset(data,select = c(&quot;price&quot;
                                  ,&quot;cancellation_policy&quot; 
                                  ,&quot;is_business_travel_ready&quot;
                                  ,&quot;accommodates&quot; 
                                  ,&quot;bedrooms&quot;
                                  ,&quot;beds&quot;
                                  ,&quot;bathrooms&quot;
                                  ,&quot;number_of_reviews&quot;
                                  ,&quot;instant_bookable&quot; 
                                  ,&quot;review_scores_rating&quot;
                                  ,&quot;review_scores_location&quot;
                                  ,&quot;review_scores_cleanliness&quot;
                                  ,&quot;review_scores_checkin&quot;
                                  ,&quot;review_scores_value&quot;
                                  ,&quot;neighbourhood_group_cleansed&quot;
                                  ,&quot;neighbourhood_cleansed&quot;
                                  ,&quot;room_type&quot;
                                  ,&quot;availability_30&quot;
                                  ,&quot;availability_365&quot;
                                  ,&quot;calculated_host_listings_count&quot;
                                  ,&quot;reviews_per_month&quot; 
                                  ,&quot;host_is_superhost&quot;
                                  ,&quot;host_identity_verified&quot;
                                  ,&quot;host_listings_count&quot;
                                  ,&quot;cleaning_fee&quot;
                                  ,&quot;guests_included&quot;
                                  ,&quot;zipcode&quot;
                                  ,&quot;property_type&quot;))</code></pre>
</div>
<div id="take-out-all-observations-with-price-equal-to-0-and-0-days-availbility-within-the-next-year.-also-check-and-remove-any-observations-with-nas-as-values" class="section level4">
<h4>Take out all observations with Price equal to $0 and 0 days availbility within the next year. Also, check and remove any observations with NA’s as values</h4>
<pre class="r"><code>non0data &lt;- subset(trimData, price != 0 &amp; availability_365 != 0)
sapply(non0data, function(x) sum(is.na(x)))</code></pre>
<pre><code>##                          price            cancellation_policy 
##                              0                              0 
##       is_business_travel_ready                   accommodates 
##                              0                              0 
##                       bedrooms                           beds 
##                              0                              9 
##                      bathrooms              number_of_reviews 
##                              0                              0 
##               instant_bookable           review_scores_rating 
##                              0                              0 
##         review_scores_location      review_scores_cleanliness 
##                              0                              0 
##          review_scores_checkin            review_scores_value 
##                              0                              0 
##   neighbourhood_group_cleansed         neighbourhood_cleansed 
##                              0                              0 
##                      room_type                availability_30 
##                              0                              0 
##               availability_365 calculated_host_listings_count 
##                              0                              0 
##              reviews_per_month              host_is_superhost 
##                              0                              0 
##         host_identity_verified            host_listings_count 
##                              0                              0 
##                   cleaning_fee                guests_included 
##                           2904                              0 
##                        zipcode                  property_type 
##                              0                              0</code></pre>
<pre class="r"><code>non0data &lt;- non0data[complete.cases(non0data),]</code></pre>
</div>
<div id="lets-take-a-look-at-the-big-picture-of-our-variables-once-more-to-double-check-that-nothing-is-off" class="section level4">
<h4>Let’s take a look at the big picture of our variables once more to double check that nothing is off</h4>
<pre class="r"><code>str(non0data)</code></pre>
<pre><code>## &#39;data.frame&#39;:    17361 obs. of  28 variables:
##  $ price                         : int  95 70 104 374 60 175 90 60 195 269 ...
##  $ cancellation_policy           : Factor w/ 5 levels &quot;flexible&quot;,&quot;moderate&quot;,..: 2 1 2 3 3 3 3 1 3 2 ...
##  $ is_business_travel_ready      : Factor w/ 2 levels &quot;f&quot;,&quot;t&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ accommodates                  : int  2 2 2 5 3 2 4 2 1 2 ...
##  $ bedrooms                      : int  1 1 1 2 1 0 1 1 0 1 ...
##  $ beds                          : int  1 1 1 5 2 1 2 1 1 1 ...
##  $ bathrooms                     : num  1 1 1 1 3 1 1 1 1 1 ...
##  $ number_of_reviews             : int  101 8 4 16 37 1 2 11 3 69 ...
##  $ instant_bookable              : Factor w/ 2 levels &quot;f&quot;,&quot;t&quot;: 2 2 1 1 2 2 2 1 1 1 ...
##  $ review_scores_rating          : int  93 89 87 95 93 100 100 89 100 97 ...
##  $ review_scores_location        : int  8 9 10 10 9 10 10 9 10 10 ...
##  $ review_scores_cleanliness     : int  9 10 9 9 9 10 8 9 10 10 ...
##  $ review_scores_checkin         : int  10 9 10 10 10 10 10 10 10 10 ...
##  $ review_scores_value           : int  9 9 10 9 9 10 10 9 10 10 ...
##  $ neighbourhood_group_cleansed  : Factor w/ 5 levels &quot;Bronx&quot;,&quot;Brooklyn&quot;,..: 3 3 3 3 1 3 2 1 3 3 ...
##  $ neighbourhood_cleansed        : Factor w/ 212 levels &quot;Allerton&quot;,&quot;Arden Heights&quot;,..: 59 200 195 196 76 172 89 199 196 142 ...
##  $ room_type                     : Factor w/ 3 levels &quot;Entire home/apt&quot;,..: 2 2 1 1 2 1 1 2 1 1 ...
##  $ availability_30               : int  3 12 4 27 22 3 10 29 0 6 ...
##  $ availability_365              : int  74 182 244 362 357 22 10 364 9 313 ...
##  $ calculated_host_listings_count: int  3 1 1 1 5 1 1 1 1 1 ...
##  $ reviews_per_month             : num  2.33 1 0.17 0.54 3.03 0.48 0.63 1.3 0.13 3.07 ...
##  $ host_is_superhost             : Factor w/ 2 levels &quot;f&quot;,&quot;t&quot;: 2 1 1 1 1 1 1 1 1 2 ...
##  $ host_identity_verified        : Factor w/ 2 levels &quot;f&quot;,&quot;t&quot;: 2 1 2 2 2 1 1 1 1 2 ...
##  $ host_listings_count           : int  3 1 1 1 5 1 1 1 1 1 ...
##  $ cleaning_fee                  : int  50 20 60 200 20 100 35 25 70 120 ...
##  $ guests_included               : int  2 1 1 1 2 1 2 1 1 2 ...
##  $ zipcode                       : Factor w/ 190 levels &quot;&quot;,&quot;07002&quot;,&quot;07093&quot;,..: 31 35 44 25 81 17 120 80 25 16 ...
##  $ property_type                 : Factor w/ 35 levels &quot;Aparthotel&quot;,&quot;Apartment&quot;,..: 2 2 2 2 20 2 2 2 2 2 ...</code></pre>
</div>
<div id="we-can-notice-that-under-zip-codes-there-is-a-zip-code-titled-with-no-value.-lets-take-a-closer-look" class="section level4">
<h4>We can notice that under zip codes, there is a zip code titled “” with no value. Let’s take a closer look</h4>
<pre class="r"><code>length(non0data$zipcode[non0data$zipcode == &quot;&quot;])</code></pre>
<pre><code>## [1] 202</code></pre>
<ul>
<li>We have 202 listings with no zip code. Since zip code can play a large role in the listing price, we will also take these listings out.</li>
</ul>
<pre class="r"><code>non0data$zipcode[non0data$zipcode == &quot;&quot;] &lt;- NA
non0data &lt;- non0data[complete.cases(non0data),]</code></pre>
</div>
<div id="now-that-we-have-cleaned-all-of-our-data-we-are-ready-to-begin-creating-the-model" class="section level4">
<h4>Now that we have cleaned all of our data, we are ready to begin creating the model</h4>
<ul>
<li>As expected, this model has a very high R^2 of .7709 most likely due to the fact that we have 26 independent variables. We notice that not all are statistically significant so we begin to remove those from the model.</li>
</ul>
<pre class="r"><code>model2 = lm(log(price)~log(accommodates)
           +bedrooms 
           +beds
           +bathrooms 
           +log(number_of_reviews)
           +review_scores_rating 
           +review_scores_location
           +review_scores_cleanliness 
           +log(review_scores_value)
           +neighbourhood_group_cleansed + room_type
           +availability_30 
           +availability_365
           +calculated_host_listings_count 
           +log(reviews_per_month) 
           +host_is_superhost
           +host_identity_verified
           +cleaning_fee
           +guests_included
           +zipcode
           +property_type
           ,non0data)</code></pre>
<ul>
<li>Although model2 still has a very high R^2 of .7705, it still also has a lot of insignificant variables due to the fact that zip code consists of 190 levels and property_type has a bunch of insignificant property_types. I will substitute zip code for neighborhood_group_cleansed since it has 4 levels compared to 190 and I will remove all insignificant property_types.</li>
</ul>
<pre class="r"><code>uncommon_listings &lt;- c(&quot;Tiny house&quot;, &quot;Earth house&quot;, &quot;Tent&quot;, &quot;Timeshare&quot;, &quot;Boat&quot;, &quot;Chalet&quot;, &quot;Hostel&quot;, &quot;Train&quot;, &quot;Cabin&quot;, &quot;Treehouse&quot;, &quot;Bungalow&quot;, &quot;Castle&quot;, &quot;Bed and breakfast&quot;, &quot;Cave&quot;, &quot;Casa particular (Cuba)&quot;, &quot;Villa&quot;, &quot;Boutique hotel&quot;, &quot;Other&quot;, &quot;In-law&quot;, &quot;Camper/RV&quot;, &quot;Yurt&quot;)

for (i in uncommon_listings){
  non0data &lt;- subset(non0data, property_type != i)
}</code></pre>
</div>
<div id="run-model-3-and-veiw-summary-coefficients" class="section level4">
<h4>Run Model 3 and veiw summary / coefficients</h4>
<pre class="r"><code>model3 = lm(log(price)~log(accommodates)
           +bedrooms 
           +beds
           +bathrooms 
           +log(number_of_reviews)
           +review_scores_rating 
           +neighbourhood_group_cleansed + room_type
           +availability_30 
           +availability_365
           +calculated_host_listings_count 
           +host_is_superhost
           +host_identity_verified
           +cleaning_fee
           +guests_included
           +property_type
           ,non0data)
summary(model3)</code></pre>
<pre><code>## 
## Call:
## lm(formula = log(price) ~ log(accommodates) + bedrooms + beds + 
##     bathrooms + log(number_of_reviews) + review_scores_rating + 
##     neighbourhood_group_cleansed + room_type + availability_30 + 
##     availability_365 + calculated_host_listings_count + host_is_superhost + 
##     host_identity_verified + cleaning_fee + guests_included + 
##     property_type, data = non0data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.0552 -0.2266 -0.0001  0.2291  2.4700 
## 
## Coefficients:
##                                             Estimate Std. Error t value
## (Intercept)                                3.868e+00  1.882e-01  20.548
## log(accommodates)                          2.185e-01  8.910e-03  24.525
## bedrooms                                   1.152e-01  5.528e-03  20.836
## beds                                      -2.495e-02  4.134e-03  -6.037
## bathrooms                                  8.751e-02  7.065e-03  12.386
## log(number_of_reviews)                    -1.359e-02  2.233e-03  -6.086
## review_scores_rating                       5.492e-03  4.037e-04  13.602
## neighbourhood_group_cleansedBrooklyn       2.498e-01  1.999e-02  12.497
## neighbourhood_group_cleansedManhattan      5.795e-01  2.025e-02  28.621
## neighbourhood_group_cleansedQueens         1.542e-01  2.108e-02   7.317
## neighbourhood_group_cleansedStaten Island -5.315e-02  3.820e-02  -1.391
## room_typePrivate room                     -5.025e-01  8.026e-03 -62.614
## room_typeShared room                      -9.280e-01  2.114e-02 -43.902
## availability_30                            4.908e-03  2.933e-04  16.731
## availability_365                           1.734e-04  2.542e-05   6.822
## calculated_host_listings_count            -2.096e-02  1.526e-03 -13.737
## host_is_superhostt                         4.006e-02  7.183e-03   5.577
## host_identity_verifiedt                    4.739e-02  5.981e-03   7.923
## cleaning_fee                               2.737e-03  8.073e-05  33.908
## guests_included                            2.233e-02  2.719e-03   8.215
## property_typeApartment                    -4.753e-01  1.826e-01  -2.602
## property_typeCondominium                  -2.917e-01  1.843e-01  -1.582
## property_typeDorm                         -5.252e-01  2.237e-01  -2.348
## property_typeGuest suite                  -5.082e-01  1.873e-01  -2.713
## property_typeGuesthouse                   -6.010e-01  1.952e-01  -3.078
## property_typeHotel                         4.794e-01  2.109e-01   2.273
## property_typeHouse                        -5.185e-01  1.828e-01  -2.836
## property_typeLoft                         -3.095e-01  1.834e-01  -1.688
## property_typeResort                        5.806e-01  2.791e-01   2.080
## property_typeServiced apartment           -3.504e-01  1.867e-01  -1.877
## property_typeTownhouse                    -5.195e-01  1.832e-01  -2.836
## property_typeVacation home                -3.264e-01  2.358e-01  -1.384
##                                           Pr(&gt;|t|)    
## (Intercept)                                &lt; 2e-16 ***
## log(accommodates)                          &lt; 2e-16 ***
## bedrooms                                   &lt; 2e-16 ***
## beds                                      1.60e-09 ***
## bathrooms                                  &lt; 2e-16 ***
## log(number_of_reviews)                    1.18e-09 ***
## review_scores_rating                       &lt; 2e-16 ***
## neighbourhood_group_cleansedBrooklyn       &lt; 2e-16 ***
## neighbourhood_group_cleansedManhattan      &lt; 2e-16 ***
## neighbourhood_group_cleansedQueens        2.65e-13 ***
## neighbourhood_group_cleansedStaten Island  0.16414    
## room_typePrivate room                      &lt; 2e-16 ***
## room_typeShared room                       &lt; 2e-16 ***
## availability_30                            &lt; 2e-16 ***
## availability_365                          9.31e-12 ***
## calculated_host_listings_count             &lt; 2e-16 ***
## host_is_superhostt                        2.49e-08 ***
## host_identity_verifiedt                   2.46e-15 ***
## cleaning_fee                               &lt; 2e-16 ***
## guests_included                           2.27e-16 ***
## property_typeApartment                     0.00927 ** 
## property_typeCondominium                   0.11363    
## property_typeDorm                          0.01889 *  
## property_typeGuest suite                   0.00668 ** 
## property_typeGuesthouse                    0.00208 ** 
## property_typeHotel                         0.02306 *  
## property_typeHouse                         0.00457 ** 
## property_typeLoft                          0.09146 .  
## property_typeResort                        0.03751 *  
## property_typeServiced apartment            0.06052 .  
## property_typeTownhouse                     0.00458 ** 
## property_typeVacation home                 0.16630    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.3648 on 16921 degrees of freedom
## Multiple R-squared:  0.7008, Adjusted R-squared:  0.7003 
## F-statistic:  1278 on 31 and 16921 DF,  p-value: &lt; 2.2e-16</code></pre>
<ul>
<li>After making the above adjustments, we now have a model with what I believe is the most significant variables to price, with a strong R^2 of .7016.</li>
</ul>
</div>
<div id="now-lets-check-if-our-model-suffers-from-multicollinearity" class="section level4">
<h4>Now, Lets check if our model suffers from multicollinearity</h4>
<pre><code>##                                    GVIF Df GVIF^(1/(2*Df))
## log(accommodates)              3.196882  1        1.787983
## bedrooms                       2.377752  1        1.541996
## beds                           3.286292  1        1.812813
## bathrooms                      1.299605  1        1.140002
## log(number_of_reviews)         1.231469  1        1.109716
## review_scores_rating           1.133861  1        1.064829
## neighbourhood_group_cleansed   1.346497  4        1.037888
## room_type                      2.162723  2        1.212691
## availability_30                1.298710  1        1.139609
## availability_365               1.317227  1        1.147705
## calculated_host_listings_count 1.254099  1        1.119866
## host_is_superhost              1.176190  1        1.084523
## host_identity_verified         1.063782  1        1.031398
## cleaning_fee                   1.834980  1        1.354614
## guests_included                1.674120  1        1.293878
## property_type                  1.411973 12        1.014478</code></pre>
<ul>
<li>Our full model does not suffer from multicollinearity as the highest VIF value of 3.1968816 is well below 5.</li>
</ul>
</div>
<div id="next-we-want-to-check-if-our-final-full-model-suffers-from-autocorrelation-or-not-using-the-durbin-watson-test." class="section level4">
<h4>Next, we want to check if our final full model suffers from autocorrelation or not using the Durbin Watson Test.</h4>
<pre><code>##  lag Autocorrelation D-W Statistic p-value
##    1      0.01476564      1.970464   0.046
##  Alternative hypothesis: rho != 0</code></pre>
<ul>
<li>Using the D-W Significance table, we can reject the null and there is no correlation among the residuals. Having a total of 16 independent variables, or k, and WELL over 200 observations, or n in our sample, the DL @ 5% significance is 1.599 and Du is 1.943 which our D-W Statistic of 1.9704635 is above the upper limit indicating no autocorrelation exists. It is also significant at the 1% with DL at 1.507 and Du at 1.847.</li>
</ul>
</div>
<div id="lets-look-at-some-visualizations" class="section level4">
<h4>Let’s look at some visualizations</h4>
<ul>
<li>Specifically the residuals from our model. In the first plot, values on the Y axis above 0 mean the prediction was too low, and negative values mean the prediction was too high. 0 means the prediction was 100% correct. We want to see something that is symmetrically distributed, tending to cluster towards the middle of the plot. On the X axis, we want to see it clustered around the lower single digit area and not something like -10 to +10.</li>
</ul>
<p><img src="/post/2018-11-19-ml-airbnb-prices_files/figure-html/unnamed-chunk-8-1.png" width="672" /><img src="/post/2018-11-19-ml-airbnb-prices_files/figure-html/unnamed-chunk-8-2.png" width="672" /></p>
<ul>
<li>Our residuals fit the requirements we would like to see which shows that our model is strong and we cannot really make this model significantly more accurate.</li>
</ul>
</div>
<div id="now-lets-input-some-sample-data-to-test-and-see-the-expected-value-in-price-our-model-gives-us." class="section level4">
<h4>Now let’s input some sample data to test and see the expected value in price our model gives us.</h4>
<ul>
<li>I created a data frame with my apartment’s information, and replaced all my NA values with .0000001, or almost 0. For example, I do not have a review score as I do not list on Airbnb, so I replaced that with almost 0. Same for my listings count. As for reviews, I inserted 1 since we take the log of this variable to normalize, and the log of 1 is equal to 0. I estimated that my listing will be available for 50% of the year and 50% of the month.</li>
</ul>
<pre class="r"><code>Jaggerslisting &lt;- data.frame(accommodates=6, number_of_reviews=1
                             ,review_scores_rating=.0000001,availability_30=15
                             ,availability_365=182, bedrooms=1, beds=2
                             ,calculated_host_listings_count=.0000001, 
                             bathrooms=1, neighbourhood_group_cleansed=&quot;Brooklyn&quot;, 
                             room_type= &quot;Entire home/apt&quot; , host_identity_verified=&quot;t&quot;, cleaning_fee=50, guests_included= 6, property_type=&quot;Apartment&quot;,host_is_superhost=&quot;f&quot;)


JaggerslistingPrice &lt;- predict(model3, newdata = Jaggerslisting)

#Since we log(price), we will need to take Exp(Of Our Result) to find our expected listing price per day per our model.

exp(JaggerslistingPrice)</code></pre>
<pre><code>##        1 
## 100.5171</code></pre>
<ul>
<li><strong>$100.5170614 as a listing price, not bad! Except I live in New York so if I hit the goal of 50% booking in the month, I will barely break even.</strong></li>
</ul>
</div>
<div id="lets-predict-with-a-95-confidence-interval-with-5-level-of-sig.-we-can-be-95-certain-that-the-range-of-values-will-contain-the-true-mean-of-the-population." class="section level4">
<h4>Lets predict with a 95% confidence interval with 5% level of sig. We can be 95% certain that the range of values will contain the true mean of the population.</h4>
<pre><code>##        fit      lwr      upr
## 1 100.5171 92.69864 108.9949</code></pre>
<ul>
<li>Since we are more focused on individual listings in our population, we can use the prediction interval. This will give us the range that we can be 95% certain the next value will fall between the intervals, and 5% will either fall under or over the intervals. We need to include uncertainty in the variation about our mean so this interval will be wider than our confidence interval.</li>
</ul>
<pre class="r"><code>predInterval &lt;- predict(model3, newdata = Jaggerslisting, interval = &quot;prediction&quot;, level = 0.95)
exp(predInterval)</code></pre>
<pre><code>##        fit      lwr      upr
## 1 100.5171 48.94546 206.4273</code></pre>
<blockquote>
<p>Please note that this is quite a bit wider than the confidence interval, indicating that the variation about the mean is fairly large. This means the datapoints of price are very spread out from the mean, indicating there is possibly more to the listing price than the variables used. I believe this ties into what I found in my research which was that commercial operators are saturating the Airbnb market, espeically in NYC.</p>
</blockquote>
</div>
<div id="finally-teaching-the-machine-to-learn-airbnb-prices" class="section level4">
<h4>Finally, Teaching the Machine to Learn Airbnb Prices</h4>
<ul>
<li>Even with all the factors I have in my model, I expect a high RMSE due to the fact that Airbnb prices have been diluted to commercial operators. If not, then with about 13,600 (n * 0.80) observations in our training data, our model should be able to predict the price a little more accurately in our test data which will result in a LOW RMSE.</li>
</ul>
<pre class="r"><code>set.seed(99)
split &lt;- sample.split(non0data$price, SplitRatio = 0.80)
train &lt;- subset(non0data, split == 1)  
test &lt;- subset(non0data, split == 0)

predictTest &lt;- predict(model3, type = &quot;response&quot;, newdata=test)
dollar_predictTest &lt;- exp(predictTest)
head(dollar_predictTest)</code></pre>
<pre><code>##        12        32        40        42        45        50 
##  51.97977  82.90947  74.48427 227.43339 113.94938 293.66290</code></pre>
<pre class="r"><code>rmse(test$price, dollar_predictTest)</code></pre>
<pre><code>## [1] 67.43659</code></pre>
<div id="the-rmse-here-is-still-high-in-my-opinion-after-training-the-model-with-13600-observations.-i-would-not-seek-a-rmse-of-67.4365899-to-efficiently-price-my-property-and-this-is-mostly-because-our-model-is-getting-trained-to-price-propertys-a-bit-low-due-to-those-commercial-operators-saturing-the-market-with-low-price-listings.-i-noticed-that-when-the-of-reviews-increase-the-price-for-the-listing-slightly-decreases.-this-can-either-mean-the-model-is-not-correct-for-this-type-of-data-or-that-since-commercial-operators-generally-price-very-low-they-tend-to-have-a-lot-of-transactions-which-results-in-more-reviews-than-the-average-lister." class="section level5">
<h5>The RMSE here is still high in my opinion after training the model with 13,600 observations. I would not seek a RMSE of 67.4365899 to efficiently price my property, and this is mostly because our model is getting trained to price property’s a bit low due to those commercial operators saturing the market with low price listings. I noticed that when the # of reviews increase, the price for the listing slightly decreases. This can either mean the model is not correct for this type of data, or that since commercial operators generally price very low they tend to have a lot of transactions which results in more reviews than the average lister.</h5>
</div>
</div>
</div>
<div id="conclusion" class="section level1">
<h1>Conclusion</h1>
<p>These commercial operators are bringing down the prices of Airbnb listings and true home sharers cannot compete. In fact, 10% of these hosts (about 5,000) earned 48% of NYC’s total Airbnb revenue totaling $318 Million while the bottom 80% (over 40400) earned $209 Million in 2017. I believe once the playing field is leveled between consumer hosts and commercial hosts, the variance between individual fitted values and the population mean will start to decrease and the listing prices can be predicted with less noise.</p>
</div>

              
            </div>
          </div>
          <div id="post-footer" class="post-footer main-content-wrap">
            
              
                
                
                  <div class="post-footer-tags">
                    <span class="text-color-light text-small">TAGGED IN</span><br/>
                    
  <a class="tag tag--primary tag--small" href="/tags/project/">Project</a>

  <a class="tag tag--primary tag--small" href="/tags/machine-learning/">Machine Learning</a>

  <a class="tag tag--primary tag--small" href="/tags/airbnb/">Airbnb</a>

  <a class="tag tag--primary tag--small" href="/tags/price-predictions/">Price Predictions</a>

  <a class="tag tag--primary tag--small" href="/tags/programming/">Programming</a>

                  </div>
                
              
            
            <div class="post-actions-wrap">
  
      <nav >
        <ul class="post-actions post-action-nav">
          
            <li class="post-action">
              
                <a class="post-action-btn btn btn--default tooltip--top" href="/2018/11/salesforce-enough-to-buy/" data-tooltip="Salesforce, Inc. - Are Expanding Margins Enough to Buy?">
              
                  <i class="fa fa-angle-left"></i>
                  <span class="hide-xs hide-sm text-small icon-ml">NEXT</span>
                </a>
            </li>
            <li class="post-action">
              
                <a class="post-action-btn btn btn--default tooltip--top" href="/2018/11/why-a-blog/" data-tooltip="Why a Blog?">
              
                  <span class="hide-xs hide-sm text-small icon-mr">PREVIOUS</span>
                  <i class="fa fa-angle-right"></i>
                </a>
            </li>
          
        </ul>
      </nav>
    <ul class="post-actions post-action-share" >
      
        <li class="post-action hide-lg hide-md hide-sm">
          <a class="post-action-btn btn btn--default btn-open-shareoptions" href="#btn-open-shareoptions">
            <i class="fa fa-share-alt"></i>
          </a>
        </li>
        
          <li class="post-action hide-xs">
            <a class="post-action-btn btn btn--default" target="new" href="https://www.facebook.com/sharer/sharer.php?url=/2018/11/ml-airbnb-prices/">
              <i class="fa fa-facebook-official"></i>
            </a>
          </li>
        
          <li class="post-action hide-xs">
            <a class="post-action-btn btn btn--default" target="new" href="https://twitter.com/intent/tweet?text=/2018/11/ml-airbnb-prices/">
              <i class="fa fa-twitter"></i>
            </a>
          </li>
        
          <li class="post-action hide-xs">
            <a class="post-action-btn btn btn--default" target="new" href="https://plus.google.com/share?url=/2018/11/ml-airbnb-prices/">
              <i class="fa fa-google-plus"></i>
            </a>
          </li>
        
      
      
        <li class="post-action">
          <a class="post-action-btn btn btn--default" href="#disqus_thread">
            <i class="fa fa-comment-o"></i>
          </a>
        </li>
      
      <li class="post-action">
        
          <a class="post-action-btn btn btn--default" href="#">
        
          <i class="fa fa-list"></i>
        </a>
      </li>
    </ul>
  
</div>

            
              
                <div id="disqus_thread">
  <noscript>Please enable JavaScript to view the <a href="//disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
</div>
              
            
          </div>
        </article>
        <footer id="footer" class="main-content-wrap">
  <span class="copyrights">
    &copy; 2018 Jagger Villalobos. All Rights Reserved
  </span>
</footer>

      </div>
      <div id="bottom-bar" class="post-bottom-bar" data-behavior="4">
        <div class="post-actions-wrap">
  
      <nav >
        <ul class="post-actions post-action-nav">
          
            <li class="post-action">
              
                <a class="post-action-btn btn btn--default tooltip--top" href="/2018/11/salesforce-enough-to-buy/" data-tooltip="Salesforce, Inc. - Are Expanding Margins Enough to Buy?">
              
                  <i class="fa fa-angle-left"></i>
                  <span class="hide-xs hide-sm text-small icon-ml">NEXT</span>
                </a>
            </li>
            <li class="post-action">
              
                <a class="post-action-btn btn btn--default tooltip--top" href="/2018/11/why-a-blog/" data-tooltip="Why a Blog?">
              
                  <span class="hide-xs hide-sm text-small icon-mr">PREVIOUS</span>
                  <i class="fa fa-angle-right"></i>
                </a>
            </li>
          
        </ul>
      </nav>
    <ul class="post-actions post-action-share" >
      
        <li class="post-action hide-lg hide-md hide-sm">
          <a class="post-action-btn btn btn--default btn-open-shareoptions" href="#btn-open-shareoptions">
            <i class="fa fa-share-alt"></i>
          </a>
        </li>
        
          <li class="post-action hide-xs">
            <a class="post-action-btn btn btn--default" target="new" href="https://www.facebook.com/sharer/sharer.php?url=/2018/11/ml-airbnb-prices/">
              <i class="fa fa-facebook-official"></i>
            </a>
          </li>
        
          <li class="post-action hide-xs">
            <a class="post-action-btn btn btn--default" target="new" href="https://twitter.com/intent/tweet?text=/2018/11/ml-airbnb-prices/">
              <i class="fa fa-twitter"></i>
            </a>
          </li>
        
          <li class="post-action hide-xs">
            <a class="post-action-btn btn btn--default" target="new" href="https://plus.google.com/share?url=/2018/11/ml-airbnb-prices/">
              <i class="fa fa-google-plus"></i>
            </a>
          </li>
        
      
      
        <li class="post-action">
          <a class="post-action-btn btn btn--default" href="#disqus_thread">
            <i class="fa fa-comment-o"></i>
          </a>
        </li>
      
      <li class="post-action">
        
          <a class="post-action-btn btn btn--default" href="#">
        
          <i class="fa fa-list"></i>
        </a>
      </li>
    </ul>
  
</div>

      </div>
      <div id="share-options-bar" class="share-options-bar" data-behavior="4">
  <i id="btn-close-shareoptions" class="fa fa-close"></i>
  <ul class="share-options">
    
      <li class="share-option">
        <a class="share-option-btn" target="new" href="https://www.facebook.com/sharer/sharer.php?url=%2F2018%2F11%2Fml-airbnb-prices%2F">
          <i class="fa fa-facebook-official"></i><span>Share on Facebook</span>
        </a>
      </li>
    
      <li class="share-option">
        <a class="share-option-btn" target="new" href="https://twitter.com/intent/tweet?text=%2F2018%2F11%2Fml-airbnb-prices%2F">
          <i class="fa fa-twitter"></i><span>Share on Twitter</span>
        </a>
      </li>
    
      <li class="share-option">
        <a class="share-option-btn" target="new" href="https://plus.google.com/share?url=%2F2018%2F11%2Fml-airbnb-prices%2F">
          <i class="fa fa-google-plus"></i><span>Share on Google&#43;</span>
        </a>
      </li>
    
  </ul>
</div>
<div id="share-options-mask" class="share-options-mask"></div>
    </div>
    
    <div id="about">
  <div id="about-card">
    <div id="about-btn-close">
      <i class="fa fa-remove"></i>
    </div>
    
      <img id="about-card-picture" src="https://res.cloudinary.com/dyackvnwm/image/upload/v1542411893/profilepic.png" alt="Author&#39;s picture" />
    
    <h4 id="about-card-name">Jagger Villalobos</h4>
    
      <div id="about-card-bio">Model &amp; Forecast | Bottom-Up Investor | Equity Researcher</div>
    
    
      <div id="about-card-job">
        <i class="fa fa-briefcase"></i>
        <br/>
        Seeking
      </div>
    
    
      <div id="about-card-location">
        <i class="fa fa-map-marker"></i>
        <br/>
        New York
      </div>
    
  </div>
</div>

    <div id="algolia-search-modal" class="modal-container">
  <div class="modal">
    <div class="modal-header">
      <span class="close-button"><i class="fa fa-close"></i></span>
      <a href="https://algolia.com" target="_blank" rel="noopener" class="searchby-algolia text-color-light link-unstyled">
        <span class="searchby-algolia-text text-color-light text-small">by</span>
        <img class="searchby-algolia-logo" src="https://www.algolia.com/static_assets/images/press/downloads/algolia-light.svg">
      </a>
      <i class="search-icon fa fa-search"></i>
      <form id="algolia-search-form">
        <input type="text" id="algolia-search-input" name="search"
          class="form-control input--large search-input" placeholder="Search" />
      </form>
    </div>
    <div class="modal-body">
      <div class="no-result text-color-light text-center">no post found</div>
      <div class="results">
        
        
          <div class="media">
            
            <div class="media-body">
              <a class="link-unstyled" href="/2018/12/yield-curve-fun/">
                <h3 class="media-heading">Yield Curve Inversion - Marks End to Bull Market?</h3>
              </a>
              <span class="media-meta">
                <span class="media-date text-small">
                  Dec 12, 2018
                </span>
              </span>
              <div class="media-content hide-xs font-merryweather">Going, Going, Inverted!  Yield Curve inversions are typically a leading indicator for a recession Historic analysis on inversions for specific yields since 1990 Yield Curve over 5 different time frames since the start of 2018 Takeaway from recent inversions   Yield Curve Inversion I’ve always followed bank stocks ever since I first began investing almost 6 years ago. Once I learned the 10-year and 2-year treasury spread was a profit driver for the big banks, I began to track the daily fluctuations.</div>
            </div>
            <div style="clear:both;"></div>
            <hr>
          </div>
        
          <div class="media">
            
            <div class="media-body">
              <a class="link-unstyled" href="/2018/11/salesforce-enough-to-buy/">
                <h3 class="media-heading">Salesforce, Inc. - Are Expanding Margins Enough to Buy?</h3>
              </a>
              <span class="media-meta">
                <span class="media-date text-small">
                  Nov 11, 2018
                </span>
              </span>
              <div class="media-content hide-xs font-merryweather">Salesforce, Inc.  Leader in the growing CRM market Modestly expanding margins Monetizing existing customer base  Customer Relationship Management Pioneer Whenever Customer Relationship Management is the topic of discussion, it’s almost impossible not to see Salesforce mentioned as the pioneer and leader. Salesforce currently has the largest market share of the CRM segment and is expected to continue gaining market share. Before we dig in to Salesforce specifically, let’s explore what exactly CRM is and the growth prospects.</div>
            </div>
            <div style="clear:both;"></div>
            <hr>
          </div>
        
          <div class="media">
            
            <div class="media-body">
              <a class="link-unstyled" href="/2018/11/ml-airbnb-prices/">
                <h3 class="media-heading">Teaching a Machine to Learn NYC Airbnb Prices</h3>
              </a>
              <span class="media-meta">
                <span class="media-date text-small">
                  Nov 11, 2018
                </span>
              </span>
              <div class="media-content hide-xs font-merryweather">Using Airbnb By now, most Gen Z and millenials have heard of or used Airbnb for a range of many reasons, such as looking for a place to crash or taking a vacation. I believe what won the consumer’s attention over hotels was the fact that you are getting the “homey” setting and privacy while away on vacation instead of a hotel environment. I realize not everyone wants to part ways with room service, benefits of a having full-service bar in the lobby, pool &amp; spas, sometimes a gym, and the 100+ channels, but when comparing the prices and the extra sq.</div>
            </div>
            <div style="clear:both;"></div>
            <hr>
          </div>
        
          <div class="media">
            
            <div class="media-body">
              <a class="link-unstyled" href="/2018/11/why-a-blog/">
                <h3 class="media-heading">Why a Blog?</h3>
              </a>
              <span class="media-meta">
                <span class="media-date text-small">
                  Nov 11, 2018
                </span>
              </span>
              <div class="media-content hide-xs font-merryweather">Does it work? Seems like it does. This is my first blog post! I wanted to create my own blog using R programming, R Studio, Git, and Github where I would host my personal site and opinions. These opinions will not be fabricated and will be based off my personal analysis.
Why start a blog? I have a huge passion for analyzing financial data, especially those 10-K’s and 10-Q’s!! I do not get excited from fleshing out models on excel all day, but I do get excited from the picture painted using all the tools these filings provide.</div>
            </div>
            <div style="clear:both;"></div>
            <hr>
          </div>
        
      </div>
    </div>
    <div class="modal-footer">
      <p class="results-count text-medium"
         data-message-zero="no post found"
         data-message-one="1 post found"
         data-message-other="{n} posts found">
         4 posts found
      </p>
    </div>
  </div>
</div>
    
  
    
    <div id="cover" style="background-image:url('/images/cover.jpg');"></div>
  


    
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js" integrity="sha256-/BfiIkHlHoVihZdc6TFuj7MmJ0TWcWsMXkeDFwhi0zw=" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.7/js/jquery.fancybox.min.js" integrity="sha256-GEAnjcTqVP+vBp3SSc8bEDQqvWAZMiHyUSIorrWwH50=" crossorigin="anonymous"></script>


<script src="/js/script-qi9wbxp2ya2j6p7wx1i6tgavftewndznf4v0hy2gvivk1rxgc3lm7njqb6bz.min.js"></script>


<script lang="javascript">
window.onload = updateMinWidth;
window.onresize = updateMinWidth;
document.getElementById("sidebar").addEventListener("transitionend", updateMinWidth);
function updateMinWidth() {
  var sidebar = document.getElementById("sidebar");
  var main = document.getElementById("main");
  main.style.minWidth = "";
  var w1 = getComputedStyle(main).getPropertyValue("min-width");
  var w2 = getComputedStyle(sidebar).getPropertyValue("width");
  var w3 = getComputedStyle(sidebar).getPropertyValue("left");
  main.style.minWidth = `calc(${w1} - ${w2} - ${w3})`;
}
</script>

<script>
$(document).ready(function() {
  hljs.configure({ classPrefix: '', useBR: false });
  $('pre.code-highlight > code, pre > code').each(function(i, block) {
    if (!$(this).hasClass('codeblock')) {
      $(this).addClass('codeblock');
    }
    hljs.highlightBlock(block);
  });
});
</script>


  
    
      <script>
        var disqus_config = function () {
          this.page.url = '\/2018\/11\/ml-airbnb-prices\/';
          
            this.page.identifier = '\/2018\/11\/ml-airbnb-prices\/'
          
        };
        (function() {
          
          
          if (window.location.hostname == "localhost") {
            return;
          }
          var d = document, s = d.createElement('script');
          var disqus_shortname = 'hugo-tranquilpeak-theme';
          s.src = '//' + disqus_shortname + '.disqus.com/embed.js';

          s.setAttribute('data-timestamp', +new Date());
          (d.head || d.body).appendChild(s);
        })();
      </script>
    
  




    
  </body>
</html>

